targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**/*.dart
      freezed:
        generate_for:
          - lib/**/*.dart
      json_serializable:
        generate_for:
          - lib/**/*.dart

