name: supabase_social_app
description: "A modern social media app built with Clean Architecture, Riverpod & Supabase."  
publish_to: 'none' 
version: 0.1.0 

environment:
  sdk: ^3.9.2 

dependencies:
  flutter:
    sdk: flutter  # Flutter SDK'sından al (versiyon belirtilmez)

  
  flutter_riverpod: ^3.0.0-dev.3

  
  riverpod_annotation: ^3.0.0-dev.3

  
  supabase_flutter: ^2.9.0

  
  freezed_annotation: ^3.0.0

  json_annotation: ^4.9.0

  
  go_router: ^14.6.2

  
  flutter_hooks: ^0.20.5

  
  cached_network_image: ^3.4.1

  image_picker: ^1.1.2

  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter 
  
  flutter_lints: ^5.0.0

  
  build_runner: ^2.4.13

  
  riverpod_generator: ^3.0.0-dev.3

  
  freezed: ^3.0.0

  
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true  
